//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;Atom-1_0-Schema&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///  &lt;xs:element name=&quot;feed&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;id&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/&gt;
        ///        &lt;xs:element name=&quot;title&quot; type=&quot;xs:string&quot;/&gt;
        ///        &lt;xs:element name=&quot;subtitle&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/&gt;
        ///        &lt;xs:element name=&quot;updated&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/&gt;
        ///        &lt;xs:element name=&quot;link&quot; type=&quot;xs:string&quot; minOccurs=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Atom_1_0_Schema {
            get {
                return ResourceManager.GetString("Atom_1_0_Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;RSS-1_0-Schema&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///  &lt;xs:element name=&quot;channel&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;title&quot; type=&quot;xs:string&quot;/&gt;
        ///        &lt;xs:element name=&quot;link&quot; type=&quot;xs:string&quot;/&gt;
        ///        &lt;xs:element name=&quot;description&quot; type=&quot;xs:string&quot;/&gt;
        ///        &lt;xs:element name=&quot;image&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/&gt;
        ///      &lt;/xs:sequence&gt;
        ///    &lt;/xs:complexType&gt;
        ///  &lt;/xs:element&gt;
        ///  &lt;xs:element name=&quot;i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RSS_1_0_Schema {
            get {
                return ResourceManager.GetString("RSS_1_0_Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;RSS-2_0-Schema&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name = &quot;rss&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;channel&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:sequence&gt;
        ///              &lt;xs:element name=&quot;title&quot; type=&quot;xs:string&quot; minOccurs =&quot;0&quot;/&gt;
        ///              &lt;xs:element name=&quot;link&quot; type=&quot;xs:string&quot; minOccurs =&quot;0&quot;/&gt;
        ///              &lt;xs:element name=&quot;description&quot; type=&quot;xs:string&quot; minOccurs =&quot;0&quot;/&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RSS_2_0_Schema {
            get {
                return ResourceManager.GetString("RSS_2_0_Schema", resourceCulture);
            }
        }
    }
}
